branches:
  except:
  - /^(?i:development)-.*$/

language: python
python:
- '3.6'
jobs:
  include:
  - stage: Test
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install pytest-cov coveralls
    script:
      - python WSO/configure_args.py -url $aw_url -username $aw_username -password $aw_password  -tenantcode $aw_tenantcode
      - python WSO/uem_version.py
      - python -m pytest WSO/ --cov=./ -v
    after_success:
    - coveralls
#   - stage: Deploy to PyPI
#     env:
#       secure: "11eT6XNusXxyK9It02b1tobG9I2/wEAbjyMXBbaVD4k0nTaAhCetAGjepvDnq05gjeUeteixMpE9rAGnvM2dir/B7fl4s99oDqn39xyYTOoGIUwEnkU+RwUoFqczbs4L14W8vLEGvORjFer7LArlb9dLVmHyhBnaM8eJslMHnRO9OLOYq6OGWunIylheWmm2EItj3FAXO3TTkTeLXO0wRO9G88etM0zA8rM+Rg20MplEaH9dh7wHpKWfzreTfOHlXEkd7z50CExVH3T4/AcZ1edj4CtEEyPB7IotYnNHcnq/CeKD3X6JGZpO4M05+o+bIMV6Sx0rDVc/Rfq2ofWKqJlVySGxW92Guip6/EHzSWAEvnARsgrvJ0OWEScMMYwgkxzoi7oO0U4sxQRNrZm7EeVrnRR34JCG7XNsL+WY5W4kLWm9mlI1BqsEHs9NHNmmlsIv87MD+twYkMTmWJXguii5Fbs4j5/2tKzt2dhYgT1elyPz3zH5gy09jDwV5gddau7w/coxhuWNee4Cr7qT8/ObkqQo8cWXjvVIcBxUfnFsi3zt403Ufgr1IpUkwvV2gUIvMyJjr1MedB4rsb4D3fKgF6a8xCwdOITj1S1Gllvuwa5zA3J6g+vW7sDzFnc+8cMhapGFySO0x3OGUdeVuy0d6vtjhrPVbNDv1JFlaNo="
#     language: python
#     python: 3.6
#     script:
#     - git remote rm origin
#     - git remote add origin https://${GITHUB_TOKEN}@github.com/rorymurdock/WSO-UEM-Py.git >/dev/null 2>&1
#     - git fetch
#     - git checkout master
#     - python3 increment_version.py
#     - git add -u
#     - git commit -m "[ci skip] version changed"
#     - git push --set-upstream origin master >/dev/null 2>&1
#     deploy:
#       provider: pypi
#       user: rorymurdock
#       password:
#         secure: "jETT/FRp2Koo+014TnKU+yTf5GO2vGSw5KijWyFINlCp/hAexj9ffR3AQej0H3OmLPW6NjJBrI0MnehDLPnrDm+PzcZkQyxHFdVTVnp99/Ovow3dBA2wxX1JZm07ZUX1MhSS9cFMkXHvTvFRAyo+HYAbwdm3VzCDO1kVr1UY2YxM6Wj12e1xx1o4xNrk3pdSv/4Wx2bXAk2N+fIoFJUAs7MZ7wBrHiVKH6ABr3N/+Myhbofq9av15+drURWneHLpwu33JNntvtE4LKVHfsrcIzamWHUBz03r6tkCdEA7GybvwCwx41UnwlaClHqQ5kN9q9ID57+8ZUOEX7WRnCLftasJtjlyEPAlvKofSppJlUwBzevvOrtqghzxno7WRPnb71eptZRZdKDaBuvKUHemPdo/DEqozvj02AI2OW8JSquHS/Nh5XhJASQsS0j6Ri/ytjPD97GIgGwMpKImhJwBLX+nAdsjKDERdBabJPCRLExL5P+HbkVSneewqPpBqpSdC6M3hpDHSS2gN315TgRhFd0oaj95BmatbU7+JG85ramaDz5O9np3n3xDMAGS+aBvx3aV+gwC37S4QfR2kOiPHMPk1q9h+8/27cfj/287oxi0gMWxy+K7dlnYoGh91CyL7DRrYcJ37Rhinyl/uMAdz55RZHZO7BfXXVwmZmXrz90="

# stages:
# - test
# - name: Deploy to PyPI
#   if: "(branch = master)"
