language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest-cov coveralls

# command to run tests
script:
  - python WSO/configure_args.py -url $aw_url -username $aw_username -password $aw_password  -tenantcode $aw_tenantcode
  - python WSO/uem_version.py
  - python -m pytest WSO/ --cov=./ -v
after_success:
  - coveralls