# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python3.7:
        python.version: '3.7'

steps:
- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install --user pytest pytest-azurepipelines
  displayName: 'Install dependencies'

- script: |         
   python3 -m pytest Tests/
  displayName: 'Run tests'
