# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python -m pip install --upgrade pip
    python -m pip install pytest pytest-azurepipelines
    python -m pip install 
  displayName: 'Install dependencies'

- script: |         
   pytest Tests/
  displayName: 'Run tests'
